### ISSUE TITLE
Where is the gateway code?

### ISSUE THREAD

**Issue by vplin** [fnoorian/CloudForecast15#1]
Hi, Mr. Farzad, which one is the template code for the gateway? Somehow I can't find it.

**Comment by fnoorian** [comment]
Unfortunately it is not done yet.
The plans are on the second project of https://github.com/fnoorian/Free-buck-boost/wiki/FuturePlans

**Comment by vplin** [comment]
Ah, it's in another git project? So I need to clone that one?

**Comment by fnoorian** [comment]
The gateway code is missing.
But please clone that repo too; that one has the Python drivers in it.

My reason for separating these was to have them as two standalone projects. But it seems that we are going to merge them anyway.

**Comment by vplin** [comment]
OK, perhaps it would be better to separate them in the early phase.

**Comment by vplin** [comment]
I mean you are right.

**Comment by fnoorian** [comment]
No problem.
Then let's keep the gateway code in Free-buck-boost repository.

Check https://github.com/fnoorian/Free-buck-boost/tree/master/json_client directory too.
It was based on an older design, where a "master" cloud would call the "slave" gateway to read hardware status (the opposite of what we want to do now).
Check:
- drivers/json_server.py: JSON server for a slave gateway
- json_client/fcc_client.py: example of reading hardware status as a master

The reusable code for the gateway is in  json_client/rpc_base.py which implements a simple JSON-RPC client, which you can use in gateway.

**Comment by vplin** [comment]
Has the boost-buck code been tested yet? Why I can't post issues there?

**Comment by fnoorian** [comment]
Have you cloned the repo?

And it hasn't been completely tested, but we have a few working on them.

**Comment by vplin** [comment]
Yes, I have cloned it, maybe not a big deal, but it seems have some grammar issues...

**Comment by vplin** [comment]
Does the whole project use python 3.4?

**Comment by fnoorian** [comment]
The project works with Python 3.x. Not sure if anything would break if we go from 3.4 to anything below.

Also I think because it was originally Yousif's repo that got forked, so you can only post issues in his repo, not mine. Just post issues here.

**Comment by vplin** [comment]
emm... Because I found Werkzeug does not support python 3 well currently...
http://werkzeug.pocoo.org/docs/0.11/python3/
And my IDE refuses to install this package...

**Comment by fnoorian** [comment]
Werkzeug supports Python 3.3+.

What version of Python do you have? What is your IDE?
Otherwise you wouldn't be able to use flask.

**Comment by vplin** [comment]
I'm using pycharm
I saw this on their website:

"Python 3 support in Werkzeug is currently highly experimental. Please give feedback on it and help us improve it."

Since we are at the very beginning, shall we spend some time to find some preferable platform? The last semester I spent a lot to study Django for making website, I would prefer to use Django for the website part. And for the gateway request, may be it's better to find some other packages... How do you think of this?

**Comment by vplin** [comment]
My python version is 3.4 and 2.7

**Comment by fnoorian** [comment]
I think using Django is OK.
As for the "request", have a look and see if you can find a better option. Although I doubt it.

**Comment by vplin** [comment]
Okay, I will try to install Werkzeug as well.

**Comment by fnoorian** [comment]
An elementary Datawarehouse added.
