### ISSUE TITLE
one difficulty for reading

### ISSUE THREAD

**Issue by vplin** [fnoorian/CloudForecast15#2]
I found it a bit hard to make the mock function to read from files, because it needs different responses with respect to the different queries. 

It's fine for writing.

**Comment by vplin** [comment]
The code has been pushed, just run the *_mock.py

**Comment by fnoorian** [comment]
Great.
Let me capture a few responses from the Arduino firmware. Then we can replace those self.read_line_json() with an appropriate string.

**Comment by vplin** [comment]
If I pushed new commit, can you see it?

**Comment by fnoorian** [comment]
Yes. I can see it here.
https://github.com/vplin/Free-buck-boost

**Comment by fnoorian** [comment]
Suggestions:
1. Move all mock drivers to a separate directory (for example, `mock_drivers/`)
2. For the get_identity of FCCBuckDriver and FCCBoostDriver, return
   `json.loads('{"device": "FreeChargeControlBuck", "version":1}')`
3.  For the get_identity of FCCBoostDriver,
   json.loads('{"device": "FreeChargeControlBoost", "version":1}')`
4. For the read_status function of both, return
   `json.loads('{"time": 23, "state": "off",  "target": 0.00, "pwm": 9.98, "volts_in": 0.10, "volts_out": 0.08, "amps_in": 0.01, "watts_in": 0.00}')`
5. For the MightyWatt get_identity
   `json.loads('{"device": "MightyWatt", "version":1,"FW_VERSION": "2.3.2", "BOARD_REVISION": "r2.3", "maxIdac": 10.100, "maxIadc": 10.120, "maxVdac": 31.412, "maxVadc": 31.548, "MAX_POWER": 75.000, "DVM_INPUT_RESISTANCE": 330.000, "TEMPERATURE_THRESHOLD": 110}')`
6. For the MightyWatt read_status, return:
   `json.loads('{"current": 10.150, "voltage": 31.641, "temperature": 0, "remoteStatus": 0, "loadStatus": ["CURRENT_OVERLOAD","VOLTAGE_OVERLOAD","POWER_OVERLOAD"]}')`

**Comment by vplin** [comment]
OK, I will change it.

**Comment by vplin** [comment]
The mock get identity and status have been added. Sorry a bit late, I went outside today...

**Comment by vplin** [comment]
By the way, what is a MightyWatt? It looks like a dc power supply(?). The name recalls me SuperMario, haha.

**Comment by vplin** [comment]
Or RoboWalle, hahaha~

**Comment by fnoorian** [comment]
Mock drivers seems to in good working conditions. Thanks!
